### ISSUE TITLE
ObjectMapper turns one invoice into two invoices

### ISSUE THREAD

**Issue by bsutton** [XeroAPI/Xero-Java#127]
I'm using the api to create an invoice.

The problem is that the object mapper seems to be mapping an invoice json object to two java objects.
The two resulting invoices each seem to have some but not all of the data.

The following junit test reproduces the problem.

```
package au.org.noojee.auditor.xero;

import static org.junit.Assert.fail;

import java.io.FileInputStream;
import java.io.IOException;

import org.junit.Ignore;
import org.junit.Test;

import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.xero.api.ApiClient;
import com.xero.api.JsonConfig;
import com.xero.api.RsaSignerFactory;
import com.xero.api.client.AccountingApi;
import com.xero.models.accounting.Invoice;
import com.xero.models.accounting.Invoices;

public class XeroApiTest
{


	@Test
	public void testParse() throws JsonParseException, JsonMappingException, IOException
	{

		JsonConfig config = new JsonConfig("xero/config.json");

		try (FileInputStream privateKeyStream = new FileInputStream(config.getPathToPrivateKey()))
		{
			RsaSignerFactory signerFactory = new RsaSignerFactory(privateKeyStream, config.getPrivateKeyPassword());

			// v1
			// client = new XeroClient(config, signerFactory);
			// client.setOAuthToken(config.getConsumerKey(), config.getConsumerSecret());

			// v2
			ApiClient apiClientForAccounting = new ApiClient(config.getApiUrl(), null, null, null);
			AccountingApi accountingApi = new AccountingApi(config, signerFactory);
			accountingApi.setApiClient(apiClientForAccounting);
			accountingApi.setOAuthToken(config.getConsumerKey(), config.getConsumerSecret());

			String response = "{\n" +
					"  \"Id\": \"16b152fa-9384-40ee-8d6b-31492c28531e\",\n" +
					"  \"Status\": \"OK\",\n" +
					"  \"ProviderName\": \"Auditor\",\n" +
					"  \"DateTimeUTC\": \"\\/Date(1549946492017)\\/\",\n" +
					"  \"Invoices\": [\n" +
					"    {\n" +
					"      \"Type\": \"ACCREC\",\n" +
					"      \"InvoiceID\": \"abbb5e5f-9ce7-48d4-b2f3-2b4243b480e8\",\n" +
					"      \"InvoiceNumber\": \"INV-0281\",\n" +
					"      \"Reference\": \"Support Contract Excess Charges for Period: 01-01-2019 to 31-01-2019\",\n" +
					"      \"Prepayments\": [],\n" +
					"      \"Overpayments\": [],\n" +
					"      \"AmountDue\": 288.72,\n" +
					"      \"AmountPaid\": 0.00,\n" +
					"      \"SentToContact\": false,\n" +
					"      \"CurrencyRate\": 1.000000,\n" +
					"      \"HasErrors\": false,\n" +
					"      \"IsDiscounted\": false,\n" +
					"      \"Contact\": {\n" +
					"        \"ContactID\": \"ab00f91f-3690-49be-b4d4-cbffbf4e32ad\",\n" +
					"        \"ContactStatus\": \"ACTIVE\",\n" +
					"        \"Name\": \"MySourcing\",\n" +
					"        \"FirstName\": \"May\",\n" +
					"        \"LastName\": \"Pam\",\n" +
					"        \"EmailAddress\": \"accounts@mysourcing.com\",\n" +
					"        \"BankAccountDetails\": \"\",\n" +
					"        \"Addresses\": [\n" +
					"          {\n" +
					"            \"AddressType\": \"STREET\",\n" +
					"            \"AddressLine1\": \"221 Road Rd\",\n" +
					"            \"City\": \"The Hills\",\n" +
					"            \"Region\": \"NSW\",\n" +
					"            \"PostalCode\": \"3000\",\n" +
					"            \"Country\": \"Australia\",\n" +
					"            \"AttentionTo\": \"\"\n" +
					"          },\n" +
					"          {\n" +
					"            \"AddressType\": \"POBOX\",\n" +
					"            \"AddressLine1\": \"221 Road Rd\",\n" +
					"            \"AddressLine2\": \"The Hills\",\n" +
					"            \"City\": \"NSW\",\n" +
					"            \"Region\": \"\",\n" +
					"            \"PostalCode\": \"3000\",\n" +
					"            \"Country\": \"Australia\",\n" +
					"            \"AttentionTo\": \"\"\n" +
					"          }\n" +
					"        ],\n" +
					"        \"Phones\": [\n" +
					"          {\n" +
					"            \"PhoneType\": \"DEFAULT\",\n" +
					"            \"PhoneNumber\": \"912\",\n" +
					"            \"PhoneAreaCode\": \"940\",\n" +
					"            \"PhoneCountryCode\": \"1800\"\n" +
					"          },\n" +
					"          {\n" +
					"            \"PhoneType\": \"DDI\",\n" +
					"            \"PhoneNumber\": \"912\",\n" +
					"            \"PhoneAreaCode\": \"940\",\n" +
					"            \"PhoneCountryCode\": \"1800\"\n" +
					"          },\n" +
					"          {\n" +
					"            \"PhoneType\": \"FAX\",\n" +
					"            \"PhoneNumber\": \"\",\n" +
					"            \"PhoneAreaCode\": \"\",\n" +
					"            \"PhoneCountryCode\": \"\"\n" +
					"          },\n" +
					"          {\n" +
					"            \"PhoneType\": \"MOBILE\",\n" +
					"            \"PhoneNumber\": \"1925\",\n" +
					"            \"PhoneAreaCode\": \"9051\",\n" +
					"            \"PhoneCountryCode\": \"02\"\n" +
					"          }\n" +
					"        ],\n" +
					"        \"UpdatedDateUTC\": \"\\/Date(1548128382713+0000)\\/\",\n" +
					"        \"ContactGroups\": [],\n" +
					"        \"IsSupplier\": false,\n" +
					"        \"IsCustomer\": true,\n" +
					"        \"SalesTrackingCategories\": [],\n" +
					"        \"PurchasesTrackingCategories\": [],\n" +
					"        \"PaymentTerms\": {\n" +
					"          \"Sales\": {\n" +
					"            \"Day\": 14,\n" +
					"            \"Type\": \"DAYSAFTERBILLDATE\"\n" +
					"          }\n" +
					"        },\n" +
					"        \"ContactPersons\": [],\n" +
					"        \"HasValidationErrors\": false\n" +
					"      },\n" +
					"      \"DateString\": \"2019-02-12T00:00:00\",\n" +
					"      \"Date\": \"\\/Date(1549929600000+0000)\\/\",\n" +
					"      \"DueDateString\": \"2019-11-07T00:00:00\",\n" +
					"      \"DueDate\": \"\\/Date(1573084800000+0000)\\/\",\n" +
					"      \"Status\": \"DRAFT\",\n" +
					"      \"LineAmountTypes\": \"Exclusive\",\n" +
					"      \"LineItems\": [\n" +
					"        {\n" +
					"          \"ItemCode\": \"b6b906c6-9651-ae20-651a-48ba9e\",\n" +
					"          \"Description\": \"Excess support charges. See emailed SLA Report for details\",\n" +
					"          \"UnitAmount\": 262.47,\n" +
					"          \"TaxType\": \"OUTPUT\",\n" +
					"          \"TaxAmount\": 26.25,\n" +
					"          \"LineAmount\": 262.47,\n" +
					"          \"AccountCode\": \"250.05\",\n" +
					"          \"Tracking\": [],\n" +
					"          \"Quantity\": 1.0000,\n" +
					"          \"LineItemID\": \"bb670356-3378-4253-9d9a-2585aa2ab81d\",\n" +
					"          \"ValidationErrors\": []\n" +
					"        }\n" +
					"      ],\n" +
					"      \"SubTotal\": 262.47,\n" +
					"      \"TotalTax\": 26.25,\n" +
					"      \"Total\": 288.72,\n" +
					"      \"UpdatedDateUTC\": \"\\/Date(1549946491987+0000)\\/\",\n" +
					"      \"CurrencyCode\": \"AUD\"\n" +
					"    }\n" +
					"  ]\n" +
					"}";

			

			TypeReference<Invoices> typeRef = new TypeReference<Invoices>()
			{
			};
			Invoices invoices = accountingApi.getApiClient().getObjectMapper().readValue(response, typeRef);

                       // invoices should contain a single invoice but contains two partial invoices.
			for (Invoice invoice : invoices.getInvoices())
			{
				System.out.println(invoice);
			}

		}

	}

}

```

Here is the resulting output from the above System.out

```
class Invoice {
    type: ACCREC
    contact: class Contact {
        contactID: ab00f91f-3690-49be-b4d4-cbffbf4e32ad
        contactNumber: null
        accountNumber: null
        contactStatus: ACTIVE
        name: MySourcing
        firstName: May
        lastName: Pam
        emailAddress: accounts@mysourcing.com
        skypeUserName: null
        contactPersons: null
        bankAccountDetails: 
        taxNumber: null
        accountsReceivableTaxType: null
        accountsPayableTaxType: null
        addresses: [class Address {
            addressType: STREET
            addressLine1: 221 Road Rd
            addressLine2: null
            addressLine3: null
            addressLine4: null
            city: The Hills
            region: NSW
            postalCode: 3000
            country: Australia
            attentionTo: 
        }, class Address {
            addressType: POBOX
            addressLine1: 221 Road Rd
            addressLine2: The Hills
            addressLine3: null
            addressLine4: null
            city: NSW
            region: 
            postalCode: 3000
            country: Australia
            attentionTo: 
        }]
        phones: [class Phone {
            phoneType: DEFAULT
            phoneNumber: 912
            phoneAreaCode: 940
            phoneCountryCode: 1800
        }, class Phone {
            phoneType: DDI
            phoneNumber: 912
            phoneAreaCode: 940
            phoneCountryCode: 1800
        }, class Phone {
            phoneType: FAX
            phoneNumber: 
            phoneAreaCode: 
            phoneCountryCode: 
        }, class Phone {
            phoneType: MOBILE
            phoneNumber: 1925
            phoneAreaCode: 9051
            phoneCountryCode: 02
        }]
        isSupplier: false
        isCustomer: true
        defaultCurrency: null
        xeroNetworkKey: null
        salesDefaultAccountCode: null
        purchasesDefaultAccountCode: null
        salesTrackingCategories: []
        purchasesTrackingCategories: []
        trackingCategoryName: null
        trackingCategoryOption: null
        paymentTerms: null
        updatedDateUTC: 2019-01-22T14:39:42.713+11:00
        contactGroups: []
        website: null
        brandingTheme: null
        batchPayments: null
        discount: null
        balances: null
        hasAttachments: null
        validationErrors: null
    }
    lineItems: []
    date: null
    dueDate: null
    lineAmountTypes: null
    invoiceNumber: INV-0281
    reference: Support Contract Excess Charges for Period: 01-01-2019 to 31-01-2019
    brandingThemeID: null
    url: null
    currencyCode: null
    currencyRate: 1.0
    status: null
    sentToContact: false
    expectedPaymentDate: null
    plannedPaymentDate: null
    subTotal: null
    totalTax: null
    total: null
    totalDiscount: null
    invoiceID: abbb5e5f-9ce7-48d4-b2f3-2b4243b480e8
    hasAttachments: null
    payments: null
    prepayments: []
    overpayments: []
    amountDue: 288.72
    amountPaid: 0.0
    fullyPaidOnDate: null
    amountCredited: null
    updatedDateUTC: null
    creditNotes: null
}
class Invoice {
    type: null
    contact: null
    lineItems: [class LineItem {
        lineItemID: bb670356-3378-4253-9d9a-2585aa2ab81d
        description: Excess support charges. See emailed SLA Report for details
        quantity: 1.0
        unitAmount: 262.47
        itemCode: b6b906c6-9651-ae20-651a-48ba9e
        accountCode: 250.05
        taxType: OUTPUT
        taxAmount: 26.25
        lineAmount: 262.47
        tracking: []
        discountRate: null
        repeatingInvoiceID: null
    }]
    date: 2019-02-12
    dueDate: 2019-11-07
    lineAmountTypes: Exclusive
    invoiceNumber: null
    reference: null
    brandingThemeID: null
    url: null
    currencyCode: AUD
    currencyRate: null
    status: DRAFT
    sentToContact: null
    expectedPaymentDate: null
    plannedPaymentDate: null
    subTotal: 262.47
    totalTax: 26.25
    total: 288.72
    totalDiscount: null
    invoiceID: null
    hasAttachments: null
    payments: null
    prepayments: null
    overpayments: null
    amountDue: null
    amountPaid: null
    fullyPaidOnDate: null
    amountCredited: null
    updatedDateUTC: 2019-02-12T15:41:31.987+11:00
    creditNotes: null
}

```
