### ISSUE TITLE
Invoices reported as deleted and incorrect outstanding balance

### ISSUE THREAD

**Issue by bsutton** [XeroAPI/Xero-Java#130]
I'm having two (possibly related) problems fetching invoices.

I have an invoice (INV-13940) which shows up in xero as having an outstanding balance of $275.

Issue 1).
When I pull the invoice via its ID (dc9f2bbe-2483-4b74-91ae-cb90092ad73b) via the the xero online api previewer the invoice has a status of DELETED.

The invoice is not marked as deleted in xero and the invoice appears on a statement if I print one from xero.

````
<Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Id>c1435a61-4d11-4202-8f48-ad90955f544e</Id>
  <Status>OK</Status>
  <ProviderName>Xero API Previewer</ProviderName>
  <DateTimeUTC>2019-02-24T23:41:30.4182751Z</DateTimeUTC>
  <Invoices>
    <Invoice>
      <Contact>
        <ContactID>92dd5450-fe48-451c-bb49-54d5767239ed</ContactID>
        <ContactStatus>ACTIVE</ContactStatus>
        <Name>XXXXX</Name>
        <EmailAddress>XXXXX@XXXXXX.com.au</EmailAddress>
        <Addresses>
          <Address>
            <AddressType>STREET</AddressType>
          </Address>
          <Address>
            <AddressType>POBOX</AddressType>
            <AddressLine1>YYYYY</AddressLine1>
            <City>YYYY CITY</City>
            <Region>YYYY</Region>
            <PostalCode>NNNN</PostalCode>
            <Country>Australia</Country>
          </Address>
        </Addresses>
        <Phones>
          <Phone>
            <PhoneType>DEFAULT</PhoneType>
          </Phone>
          <Phone>
            <PhoneType>DDI</PhoneType>
          </Phone>
          <Phone>
            <PhoneType>FAX</PhoneType>
          </Phone>
          <Phone>
            <PhoneType>MOBILE</PhoneType>
          </Phone>
        </Phones>
        <UpdatedDateUTC>2019-01-25T03:03:57.097</UpdatedDateUTC>
        <IsSupplier>false</IsSupplier>
        <IsCustomer>true</IsCustomer>
      </Contact>
      <Date>2018-11-06T00:00:00</Date>
      <DueDate>2018-11-21T00:00:00</DueDate>
      <Status>DELETED</Status>
      <LineAmountTypes>Inclusive</LineAmountTypes>
      <LineItems>
        <LineItem>
          <ItemCode>5274946e-b800-4b7c-8a72-58e348</ItemCode>
          <Description>XXXXXXXXXXXXXXXXXXXXXXX</Description>
          <UnitAmount>275.00</UnitAmount>
          <TaxType>OUTPUT</TaxType>
          <TaxAmount>25.00</TaxAmount>
          <LineAmount>275.00</LineAmount>
          <AccountCode>200.07</AccountCode>
          <Quantity>1.0000</Quantity>
          <LineItemID>8ad753e5-b8a0-4b7a-992c-b88f9be54ec5</LineItemID>
        </LineItem>
        <LineItem>
          <ItemCode>6a28aa03-0bea-b4ea-a89b-5031d4</ItemCode>
          <Description>National Fixed Line</Description>
          <UnitAmount>0.00</UnitAmount>
          <TaxAmount>0.00</TaxAmount>
          <LineAmount>0.00</LineAmount>
          <Quantity>1.0000</Quantity>
          <LineItemID>cf41e949-cd48-446e-865a-2d37f45e41d1</LineItemID>
        </LineItem>
        <LineItem>
          <ItemCode>6a28aa03-0bea-b4ea-a89b-5031d4</ItemCode>
          <Description>Mobile</Description>
          <UnitAmount>0.00</UnitAmount>
          <TaxAmount>0.00</TaxAmount>
          <LineAmount>0.00</LineAmount>
          <Quantity>1.0000</Quantity>
          <LineItemID>1b8cfad2-6234-4550-875c-9c34d446dc1a</LineItemID>
        </LineItem>
      </LineItems>
      <SubTotal>250.00</SubTotal>
      <TotalTax>25.00</TotalTax>
      <Total>275.00</Total>
      <UpdatedDateUTC>2018-11-13T06:33:34.473</UpdatedDateUTC>
      <CurrencyCode>AUD</CurrencyCode>
      <Type>ACCREC</Type>
      <InvoiceID>dc9f2bbe-2483-4b74-91ae-cb90092ad73b</InvoiceID>
      <InvoiceNumber>V-13490</InvoiceNumber>
      <AmountDue>275.00</AmountDue>
      <AmountPaid>0.00</AmountPaid>
      <SentToContact>false</SentToContact>
      <CurrencyRate>1.000000</CurrencyRate>
      <HasAttachments>false</HasAttachments>
    </Invoice>
  </Invoices>
</Response>
````
Issue 2)
For efficiency (and to avoid the api limiter) I fetch all outstanding invoices in a batch by paging through the invoice list:

````
https://api.xero.com/api.xro/2.0/Invoices?includeArchived=false&where=Type%20%3D%20%22ACCREC%22&page=1
````
When the same invoice is returned via this paging mechanism it appears to have two errors
1) the status is DELETED (the same as the above invoice).
2) the outstanding balance is zero (which is inconsistent with the result when I directly query the invoice via the previewer as above) and inconsistent with what xero shows which is an outstanding balance of $275.

The Invoice details (from the eclilpse debugger)

````
class Invoice {
    type: ACCREC
    contact: class Contact {
        contactID: 92dd5450-fe48-451c-bb49-54d5767239ed
        contactNumber: null
        accountNumber: null
        contactStatus: null
        name: XXXXXX
        firstName: null
        lastName: null
        emailAddress: null
        skypeUserName: null
        contactPersons: []
        bankAccountDetails: null
        taxNumber: null
        accountsReceivableTaxType: null
        accountsPayableTaxType: null
        addresses: []
        phones: []
        isSupplier: null
        isCustomer: null
        defaultCurrency: null
        xeroNetworkKey: null
        salesDefaultAccountCode: null
        purchasesDefaultAccountCode: null
        salesTrackingCategories: null
        purchasesTrackingCategories: null
        trackingCategoryName: null
        trackingCategoryOption: null
        paymentTerms: null
        updatedDateUTC: null
        contactGroups: []
        website: null
        brandingTheme: null
        batchPayments: null
        discount: null
        balances: null
        hasAttachments: null
        validationErrors: null
    }
    lineItems: [class LineItem {
        lineItemID: 8ad753e5-b8a0-4b7a-992c-b88f9be54ec5
        description: XXXXXXXXXXXXXXXXXXXXXXX
        quantity: 1.0
        unitAmount: 275.0
        itemCode: 5274946e-b800-4b7c-8a72-58e348
        accountCode: 200.07
        taxType: OUTPUT
        taxAmount: 25.0
        lineAmount: 275.0
        tracking: []
        discountRate: null
        repeatingInvoiceID: null
    }, class LineItem {
        lineItemID: cf41e949-cd48-446e-865a-2d37f45e41d1
        description: National Fixed Line
        quantity: 1.0
        unitAmount: 0.0
        itemCode: 6a28aa03-0bea-b4ea-a89b-5031d4
        accountCode: null
        taxType: null
        taxAmount: 0.0
        lineAmount: 0.0
        tracking: []
        discountRate: null
        repeatingInvoiceID: null
    }, class LineItem {
        lineItemID: 1b8cfad2-6234-4550-875c-9c34d446dc1a
        description: XXXXXX
        quantity: 1.0
        unitAmount: 0.0
        itemCode: 6a28aa03-0bea-b4ea-a89b-5031d4
        accountCode: null
        taxType: null
        taxAmount: 0.0
        lineAmount: 0.0
        tracking: []
        discountRate: null
        repeatingInvoiceID: null
    }]
    date: 2018-11-06
    dueDate: 2018-11-21
    lineAmountTypes: Inclusive
    invoiceNumber: V-13490
    reference: 
    brandingThemeID: null
    url: null
    currencyCode: AUD
    currencyRate: 1.0
    status: DELETED
    sentToContact: null
    expectedPaymentDate: null
    plannedPaymentDate: null
    subTotal: 250.0
    totalTax: 25.0
    total: 275.0
    totalDiscount: null
    invoiceID: dc9f2bbe-2483-4b74-91ae-cb90092ad73b
    hasAttachments: false
    payments: []
    prepayments: []
    overpayments: []
    amountDue: 0.0
    amountPaid: 0.0
    fullyPaidOnDate: null
    amountCredited: 0.0
    updatedDateUTC: 2018-11-13T17:33:34.473+11:00
    creditNotes: []
}
````
